---

- hosts: all
  become: true
  tasks:

  - name: update package for PopOs
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Pop!_OS"

  - name: update package for redhat
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php package
    tags: apache,apache2,php,popos
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Pop!_OS"

  - name: install apache and php package
    tags: apache,php,httpd,redhat
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: copy default html file
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode:  0644


- hosts: file_server
  become: true
  tasks:

  - name: install samba package
    tags: samba,smb,popos
    package:
      name: samba
      state: latest
