---

- hosts: all
  become: true
  pre_tasks:

  - name: update cache for PopOs
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Pop!_OS"

  - name: update cache for redhat
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"

- hosts: all
  become: true
  roles:
    - base

- hosts: workstation
  become: true
  roles:
    - workstation

- hosts: web_server
  become: true
  roles:
    - web_server


- hosts: file_server
  become: true
  roles:
    - file_server
