- name: install apache and php package
  tags: apache,apache2,php,popos
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Pop!_OS"

- name: install apache and php package
  tags: apache,php,httpd,redhat
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "RedHat"

- name: start httpd service
  tags: apache,httpd,redhat
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"

- name: change email address for admin
  tags: apache,httpd,redhat
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin root@localhost
  when: ansible_distribution == "RedHat"
  register: httpd

- name: restart httpd service
  tags: apache,httpd,redhat
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file
  tags: apache,apache2,httpd
  copy:
   src: default_site.html
   dest: /var/www/html/index.html
   owner: root
   group: root
   mode:  0644
